name: ONK
version: '1.0-SNAPSHOT'
main: io.github.tunafishyy.onk.ONK
api-version: 1.19
commands:
  aaustralija:
    description: gives grom
  katon:
    description: Stvori se katon goukakyou no jutsu.
  kresh:
    description: Crashat ce ti se MC za 4 sekunde.
